### ISSUE TITLE
reproduce the exact environment of EB in a user terminal

### ISSUE THREAD

**Issue by toxa81** [eth-cscs/production#703]
Sometimes the EB configure or build command fails, but the **same** command copy-pasted to the terminal and executed by user works. Fresh example: 
  * from the EB script: module unload cray-libsci && module load gcc/5.3.0 && module list &&  ./configure --prefix=/users/antonk/easybuild/daint/haswell/software/OTF2/2.1.1-CrayIntel-17.08 CC=cc FC=ifort CXX=icc CC_FOR_BUILD=cc CXX_FOR_BUILD=icc FC_FOR_BUILD=ifort
== 2018-07-18 09:32:09,969 build_log.py:158 ERROR EasyBuild crashed with an error
...
checking whether the C compiler works... no
configure: error: in `/dev/shm/antonk/easybuild/stage/build/OTF2/2.1.1/CrayIntel-17.08/otf2-2.1.1/build-backend':
configure: error: C compiler cannot create executables
  * from the new terminal: OK

**Comment by gppezzi** [comment]
@toxa81 the EB default environment is not exactly the same as a clean shell, since the Cray toolchains add environment variables for CC, CFLAGS and etc.

The first potential differences that I can think of are that CrayIntel uses by default: libsci, verbose enabled and dynamic builds.

One simple way of debugging is to run `eb -x your-file.eb` (extended dry-run) and identify the exports that might be conflicting with your configure environment.

**Comment by victorusu** [comment]
One thing that could be used it to provide [buildenv](https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/b/buildenv) as hidden modules on Piz Daint.
